// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "Chapitre 1",
      id: "cours/cours1", // Doit matcher le nom du document qui est dans docs/01-cours/. Les chiffres au début (ex : 01-) sont ignorés.
      customProps: { // Attention, il faut recompiler à chaque modification dans sidebar.js pour que les modifications s'appliquent.
        calendrier: {
          "Antoine": [
            {"1010": "2025-06-09"}  // Date du cours pour le groupe 1010
          ]
        },
        tooltip: "visible" // Valeurs possibles visible ou cache, valeur par défaut "visible"
      }
    },
    /*{
      type: "doc",
      label: "Laboratoire 1",
      id: "cours/labo1",
      customProps: {
        calendrier: {
          "Antoine": [
            {"1010": "2025-06-09"}, // Date du cours pour le groupe 1010
            {"1020": "2025-06-09"} // Date du cours pour le groupe 1020
          ]
        },
        tooltip: "visible"
      }
    },*/
    {
      type: "doc",
      label: "Chapitre 2",
      id: "cours/cours2",
      customProps: {
        calendrier: {
          "Antoine": [
            {"1010": "2025-06-11"}
          ]
        },
        avancementLabel: "TP1 - Créé",
        avancement: 0.0
      }
    }
  ],
  "tp": [
    {
      type: "autogenerated",
      "dirName": "02-tp"
    }
  ],
  laboratoire: [
    {
      type: "doc",
      label: "Laboratoire 1",
      id: "cours/labo1",
      customProps: {
        calendrier: {
          "Antoine": [
            {"1010": "2025-06-09"}, // Date du labo1 pour le groupe 1010
            {"1020": "2025-06-09"} // Date du labo1 pour le groupe 1020
          ]
        }
      }
    },
    {
      type: "doc",
      label: "Laboratoire 2",
      id: "cours/labo2",
      customProps: {
        calendrier: {
          "Antoine": [
            {"1010": "2025-06-09"}, // Date du labo1 pour le groupe 1010
            {"1020": "2025-06-09"} // Date du labo1 pour le groupe 1020
          ]
        }
      }
    }
  ]
};

module.exports = sidebars;
